### ISSUE TITLE
 flutter_test from sdk, version solving failed.

### ISSUE THREAD

**Issue by Ericahyana** [gmpassos/esc_pos_dart#3]
Resolving dependencies...
Because every version of flutter_test from sdk depends on collection 1.17.1 and esc_pos_dart >=1.0.2 depends on collection ^1.17.2, flutter_test from sdk is incompatible with esc_pos_dart >=1.0.2.
So, because myApp depends on both esc_pos_dart ^1.0.4 and flutter_test from sdk, version solving failed.
exit code 1

**Comment by gmpassos** [comment]
Just update your flutter:
https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml#L36

Next Flutter version uses `collection: 1.17.2` (maybe in 2 weeks)

Best regards
