### ISSUE TITLE
Could not get it working together with esc_pos_utils package 

### ISSUE THREAD

**Issue by ivankasalo** [gmpassos/esc_pos_dart#4]
Getting issue: 
Because every version of esc_pos_utils from path depends on image ^4.0.17 and every version of esc_pos_dart depends on image ^3.0.2

**Comment by gmpassos** [comment]
What version of `esc_pos_utils` are you using? since it depends on `image: ^3.0.2`

https://github.com/andrey-ushakov/esc_pos_utils/blob/master/pubspec.yaml

**Comment by ivankasalo** [comment]
My bad. I'm trying to get it working with esc_pos_utils_plus which depends on image ^4.0.17.
